from __future__ import annotations
from typing import TYPE_CHECKING
from BaseClasses import ItemClassification, Location
from . import items
if TYPE_CHECKING:
    from .world import RWBYWorld

LOCATION_NAME_TO_ID = {
    "Ruby Level 2": 100,
    "Ruby Level 3": 101,
    "Ruby Level 4": 102,
    "Ruby Level 5": 103,
    "Ruby Level 6": 104,
    "Ruby Level 7": 105,
    "Ruby Level 8": 106,
    "Ruby Level 9": 107,
    "Ruby Level 10": 108,

    "Weiss Level 2": 200,
    "Weiss Level 3": 201,
    "Weiss Level 4": 202,
    "Weiss Level 5": 203,
    "Weiss Level 6": 204,
    "Weiss Level 7": 205,
    "Weiss Level 8": 206,
    "Weiss Level 9": 207,
    "Weiss Level 10": 208,

    "Blake Level 2": 300,
    "Blake Level 3": 301,
    "Blake Level 4": 302,
    "Blake Level 5": 303,
    "Blake Level 6": 304,
    "Blake Level 7": 305,
    "Blake Level 8": 306,
    "Blake Level 9": 307,
    "Blake Level 10": 308,

    "Yang Level 2": 400,
    "Yang Level 3": 401,
    "Yang Level 4": 402,
    "Yang Level 5": 403,
    "Yang Level 6": 404,
    "Yang Level 7": 405,
    "Yang Level 8": 406,
    "Yang Level 9": 407,
    "Yang Level 10": 408,

    "Boots on the Ground - Completed": 10000,
    "Boots on the Ground - Encounter 1": 10001,
    "Boots on the Ground - Encounter 2": 10002,
    "Boots on the Ground - Encounter 3": 10003,
    "Boots on the Ground - Wave 1": 10010,
    "Boots on the Ground - Wave 2": 10011,
    "Boots on the Ground - Wave 3": 10012,
    "Boots on the Ground - Wave 4": 10013,
    "Boots on the Ground - Wave 1 Flawless": 10020,
    "Boots on the Ground - Wave 2 Flawless": 10021,
    "Boots on the Ground - Wave 3 Flawless": 10022,
    "Boots on the Ground - Wave 4 Flawless": 10023,
    "Boots on the Ground - Golden Knight": 10090,
    "Boots on the Ground - Golden Rook": 10091,
    "Boots on the Ground - Black Knight": 10092,
    "Boots on the Ground - Black Rook": 10093,
    "Boots on the Ground - Before Arena 1 Pot 1": 10100,
    "Boots on the Ground - Before Arena 1 Pot 2": 10101,
    "Boots on the Ground - Before Arena 1 Pot 3": 10102,
    "Boots on the Ground - Arena 1 Pot 1": 10103,
    "Boots on the Ground - Arena 1 Pot 2": 10104,
    "Boots on the Ground - Arena 1 Pot 3": 10105,
    "Boots on the Ground - Before Arena 2 Pot 1": 10106,
    "Boots on the Ground - Before Arena 2 Pot 2": 10107,
    "Boots on the Ground - Before Arena 2 Pot 3": 10108,
    "Boots on the Ground - Arena 2 Pot 1": 10109,
    "Boots on the Ground - Arena 2 Pot 2": 10110,
    "Boots on the Ground - Arena 2 Pot 3": 10111,
    "Boots on the Ground - Arena 2 Pot 4": 10112,
    "Boots on the Ground - Arena 2 Pot 5": 10113,
    "Boots on the Ground - Arena 2 Crate 1": 10114,
    "Boots on the Ground - Arena 2 Crate 2": 10115,
    "Boots on the Ground - Arena 2 Crate 3": 10116,
    "Boots on the Ground - Before Arena 3 Pot 1": 10117,
    "Boots on the Ground - Before Arena 3 Pot 2": 10118,
    "Boots on the Ground - Arena 3 Pot 1": 10119,
    "Boots on the Ground - Arena 3 Pot 2": 10120,
    "Boots on the Ground - Arena 3 Crate 1": 10121,
    "Boots on the Ground - Arena 3 Crate 2": 10122,
    "Boots on the Ground - Arena 3 Crate 3": 10123,
    "Boots on the Ground - Arena 3 Crate 4": 10124,
    "Boots on the Ground - By Bridge Pot 1": 10125,
    "Boots on the Ground - By Bridge Crate 1": 10126,
    "Boots on the Ground - By Bridge Crate 2": 10127,
    "Boots on the Ground - By Bridge Crate 3": 10128,
    "Boots on the Ground - By Bridge Crate 4": 10129,
    "Boots on the Ground - By Artifact Crate 1": 10130,
    "Boots on the Ground - By Artifact Crate 2": 10131,
    "Boots on the Ground - Cave Crate 1": 10132,
    "Boots on the Ground - Cave Crate 2": 10133,
    "Boots on the Ground - Cave Crate 3": 10134,

    "Technical Difficulties - Completed": 20000,
    "Technical Difficulties - Encounter 1": 20001,
    "Technical Difficulties - Encounter 2": 20002,
    "Technical Difficulties - Encounter 3A": 20003,
    "Technical Difficulties - Wave 1": 20010,
    "Technical Difficulties - Wave 2": 20011,
    "Technical Difficulties - Wave 3": 20012,
    "Technical Difficulties - Wave 4": 20013,
    "Technical Difficulties - Wave 1 Flawless": 20020,
    "Technical Difficulties - Wave 2 Flawless": 20021,
    "Technical Difficulties - Wave 3 Flawless": 20022,
    "Technical Difficulties - Wave 4 Flawless": 20023,
    "Technical Difficulties - Golden Knight": 20090,
    "Technical Difficulties - Golden Rook": 20091,
    "Technical Difficulties - Black Knight": 20092,
    "Technical Difficulties - Black Rook": 20093,
    "Technical Difficulties - By Artifact Crate 1": 20100,
    "Technical Difficulties - By Artifact Crate 2": 20101,
    "Technical Difficulties - By Artifact Crate 3": 20102,
    "Technical Difficulties - By Artifact Crate 4": 20103,
    "Technical Difficulties - Before Arena 1 Pot 1": 20104,
    "Technical Difficulties - Before Arena 1 Pot 2": 20105,
    "Technical Difficulties - Before Arena 1 Pot 3": 20106,
    "Technical Difficulties - Before Arena 1 Crate 1": 20107,
    "Technical Difficulties - Before Arena 1 Crate 2": 20108,
    "Technical Difficulties - Arena 1 Crate 1": 20109,
    "Technical Difficulties - Arena 1 Crate 2": 20110,
    "Technical Difficulties - Before Arena 2 Crate 1": 20111,
    "Technical Difficulties - Before Arena 2 Crate 2": 20112,
    "Technical Difficulties - Before Arena 2 Crate 3": 20113,
    "Technical Difficulties - Before Arena 2 Crate 4": 20114,
    "Technical Difficulties - Arena 2 Pot 1": 20115,
    "Technical Difficulties - Arena 2 Pot 2": 20116,
    "Technical Difficulties - Arena 2 Pot 3": 20117,
    "Technical Difficulties - Arena 2 Pot 4": 20118,
    "Technical Difficulties - Arena 2 Pot 5": 20119,
    "Technical Difficulties - Arena 2 Pot 6": 20120,
    "Technical Difficulties - Arena 2 Pot 7": 20121,
    "Technical Difficulties - Arena 2 Pot 8": 20122,
    "Technical Difficulties - Arena 2 Pot 9": 20123,
    "Technical Difficulties - Arena 2 Pot 10": 20124,
    "Technical Difficulties - Arena 2 Pot 11": 20125,
    "Technical Difficulties - Arena 2 Pot 12": 20126,
    "Technical Difficulties - Arena 2 Pot 13": 20127,
    "Technical Difficulties - Arena 2 Crate": 20128,
    "Technical Difficulties - Before Arena 3 Crate 1": 20129,
    "Technical Difficulties - Arena 3A Crate 1": 20130,
    "Technical Difficulties - Arena 3A Crate 2": 20131,
    "Technical Difficulties - Arena 3A Crate 3": 20132,
    "Technical Difficulties - Arena 3A Crate 4": 20133,
    "Technical Difficulties - Arena 3A Crate 5": 20134,
    "Technical Difficulties - Arena 3A Crate 6": 20135,
    "Technical Difficulties - Before Arena 4 Crate 1": 20136,
    "Technical Difficulties - Before Arena 4 Crate 2": 20137,
    "Technical Difficulties - Before Arena 4 Crate 3": 20138,
    "Technical Difficulties - Before Arena 4 Crate 4": 20139,
    "Technical Difficulties - Before Arena 4 Crate 5": 20140,
    "Technical Difficulties - Right of Arena 4 Crate 1": 20141,
    "Technical Difficulties - Right of Arena 4 Crate 2": 20142,
    "Technical Difficulties - Arena 4 Crate 1": 20143,
    "Technical Difficulties - Arena 4 Crate 2": 20144,
    "Technical Difficulties - Before Arena 2 Crate 5": 20145,
    "Technical Difficulties - Before Arena 4 Crate 6": 20146,
    "Technical Difficulties - Before Arena 4 Crate 7": 20147,

    "The Collapse - Completed": 30000,
    "The Collapse - Golden Knight": 30090,
    "The Collapse - Golden Rook": 30091,
    "The Collapse - Black Knight": 30092,
    "The Collapse - Black Rook": 30093,

    "Below the Surface - Completed": 40000,
    "Below the Surface - Golden Knight": 40090,
    "Below the Surface - Golden Rook": 40091,
    "Below the Surface - Black Knight": 40092,
    "Below the Surface - Black Rook": 40093,

    "Right on Track - Completed": 50000,
    "Right on Track - Golden Knight": 50090,
    "Right on Track - Golden Rook": 50091,
    "Right on Track - Black Knight": 50092,
    "Right on Track - Black Rook": 50093,

    "End of the Line - Completed": 60000,
    "End of the Line - Golden Knight": 60090,
    "End of the Line - Golden Rook": 60091,
    "End of the Line - Black Knight": 60092,
    "End of the Line - Black Rook": 60093,

    "The Island of Dr. Merlot - Completed": 70000,
    "The Island of Dr. Merlot - Golden Knight": 70090,
    "The Island of Dr. Merlot - Golden Rook": 70091,
    "The Island of Dr. Merlot - Black Knight": 70092,
    "The Island of Dr. Merlot - Black Rook": 70093,

    "A Grimm Discovery - Completed": 80000,
    "A Grimm Discovery - Golden Knight": 80090,
    "A Grimm Discovery - Golden Rook": 80091,
    "A Grimm Discovery - Black Knight": 80092,
    "A Grimm Discovery - Black Rook": 80093,

    "The Grand Tour - Completed": 90000,
    "The Grand Tour - Golden Knight": 90090,
    "The Grand Tour - Golden Rook": 90091,
    "The Grand Tour - Black Knight": 90092,
    "The Grand Tour - Black Rook": 90093,

    "Final Exam - Completed": 100000,
    "Final Exam - Golden Knight": 100090,
    "Final Exam - Golden Rook": 100091,
    "Final Exam - Black Knight": 100092,
    "Final Exam - Black Rook": 100093,
}

class RWBYLocation(Location):
    game = "RWBY Grimm Eclipse"

def get_location_names_with_ids(location_names: list[str]) -> dict[str, int | None]:
    return {location_name: LOCATION_NAME_TO_ID[location_name] for location_name in location_names}

def create_all_locations(world: RWBYWorld) -> None:
    world.get_region("Boots on the Ground").add_locations(get_location_names_with_ids([
        "Boots on the Ground - Completed",
        "Boots on the Ground - Encounter 1",
        "Boots on the Ground - Encounter 2",
        "Boots on the Ground - Encounter 3",
        "Boots on the Ground - Wave 1",
        "Boots on the Ground - Wave 2",
        "Boots on the Ground - Wave 3",
        "Boots on the Ground - Wave 4",
        "Boots on the Ground - Wave 1 Flawless",
        "Boots on the Ground - Wave 2 Flawless",
        "Boots on the Ground - Wave 3 Flawless",
        "Boots on the Ground - Wave 4 Flawless",
        "Boots on the Ground - Golden Knight",
        "Boots on the Ground - Golden Rook",
        "Boots on the Ground - Black Knight",
        "Boots on the Ground - Black Rook",
        "Boots on the Ground - Before Arena 1 Pot 1",
        "Boots on the Ground - Before Arena 1 Pot 2",
        "Boots on the Ground - Before Arena 1 Pot 3",
        "Boots on the Ground - Arena 1 Pot 1",
        "Boots on the Ground - Arena 1 Pot 2",
        "Boots on the Ground - Arena 1 Pot 3",
        "Boots on the Ground - Before Arena 2 Pot 1",
        "Boots on the Ground - Before Arena 2 Pot 2",
        "Boots on the Ground - Before Arena 2 Pot 3",
        "Boots on the Ground - Arena 2 Pot 1",
        "Boots on the Ground - Arena 2 Pot 2",
        "Boots on the Ground - Arena 2 Pot 3",
        "Boots on the Ground - Arena 2 Pot 4",
        "Boots on the Ground - Arena 2 Pot 5",
        "Boots on the Ground - Arena 2 Crate 1",
        "Boots on the Ground - Arena 2 Crate 2",
        "Boots on the Ground - Arena 2 Crate 3",
        "Boots on the Ground - Before Arena 3 Pot 1",
        "Boots on the Ground - Before Arena 3 Pot 2",
        "Boots on the Ground - Arena 3 Pot 1",
        "Boots on the Ground - Arena 3 Pot 2",
        "Boots on the Ground - Arena 3 Crate 1",
        "Boots on the Ground - Arena 3 Crate 2",
        "Boots on the Ground - Arena 3 Crate 3",
        "Boots on the Ground - Arena 3 Crate 4",
        "Boots on the Ground - By Bridge Pot 1",
        "Boots on the Ground - By Bridge Crate 1",
        "Boots on the Ground - By Bridge Crate 2",
        "Boots on the Ground - By Bridge Crate 3",
        "Boots on the Ground - By Bridge Crate 4",
        "Boots on the Ground - By Artifact Crate 1",
        "Boots on the Ground - By Artifact Crate 2",
        "Boots on the Ground - Cave Crate 1",
        "Boots on the Ground - Cave Crate 2",
        "Boots on the Ground - Cave Crate 3",
    ]), RWBYLocation)

    world.get_region("Technical Difficulties").add_locations(get_location_names_with_ids([
        "Technical Difficulties - Completed",
        "Technical Difficulties - Encounter 1",
        "Technical Difficulties - Encounter 2",
        "Technical Difficulties - Encounter 3A",
        "Technical Difficulties - Wave 1",
        "Technical Difficulties - Wave 2",
        "Technical Difficulties - Wave 3",
        "Technical Difficulties - Wave 4",
        "Technical Difficulties - Wave 1 Flawless",
        "Technical Difficulties - Wave 2 Flawless",
        "Technical Difficulties - Wave 3 Flawless",
        "Technical Difficulties - Wave 4 Flawless",
        "Technical Difficulties - Golden Knight",
        "Technical Difficulties - Golden Rook",
        "Technical Difficulties - Black Knight",
        "Technical Difficulties - Black Rook",
        "Technical Difficulties - By Artifact Crate 1",
        "Technical Difficulties - By Artifact Crate 2",
        "Technical Difficulties - By Artifact Crate 3",
        "Technical Difficulties - By Artifact Crate 4",
        "Technical Difficulties - Before Arena 1 Pot 1",
        "Technical Difficulties - Before Arena 1 Pot 2",
        "Technical Difficulties - Before Arena 1 Pot 3",
        "Technical Difficulties - Before Arena 1 Crate 1",
        "Technical Difficulties - Before Arena 1 Crate 2",
        "Technical Difficulties - Arena 1 Crate 1",
        "Technical Difficulties - Arena 1 Crate 2",
        "Technical Difficulties - Before Arena 2 Crate 1",
        "Technical Difficulties - Before Arena 2 Crate 2",
        "Technical Difficulties - Before Arena 2 Crate 3",
        "Technical Difficulties - Before Arena 2 Crate 4",
        "Technical Difficulties - Before Arena 2 Crate 5",
        "Technical Difficulties - Arena 2 Pot 1",
        "Technical Difficulties - Arena 2 Pot 2",
        "Technical Difficulties - Arena 2 Pot 3",
        "Technical Difficulties - Arena 2 Pot 4",
        "Technical Difficulties - Arena 2 Pot 5",
        "Technical Difficulties - Arena 2 Pot 6",
        "Technical Difficulties - Arena 2 Pot 7",
        "Technical Difficulties - Arena 2 Pot 8",
        "Technical Difficulties - Arena 2 Pot 9",
        "Technical Difficulties - Arena 2 Pot 10",
        "Technical Difficulties - Arena 2 Pot 11",
        "Technical Difficulties - Arena 2 Pot 12",
        "Technical Difficulties - Arena 2 Pot 13",
        "Technical Difficulties - Arena 2 Crate",
        "Technical Difficulties - Before Arena 3 Crate 1",
        "Technical Difficulties - Arena 3A Crate 1",
        "Technical Difficulties - Arena 3A Crate 2",
        "Technical Difficulties - Arena 3A Crate 3",
        "Technical Difficulties - Arena 3A Crate 4",
        "Technical Difficulties - Arena 3A Crate 5",
        "Technical Difficulties - Arena 3A Crate 6",
        "Technical Difficulties - Before Arena 4 Crate 1",
        "Technical Difficulties - Before Arena 4 Crate 2",
        "Technical Difficulties - Before Arena 4 Crate 3",
        "Technical Difficulties - Before Arena 4 Crate 4",
        "Technical Difficulties - Before Arena 4 Crate 5",
        "Technical Difficulties - Before Arena 4 Crate 6",
        "Technical Difficulties - Before Arena 4 Crate 7",
        "Technical Difficulties - Right of Arena 4 Crate 1",
        "Technical Difficulties - Right of Arena 4 Crate 2",
        "Technical Difficulties - Arena 4 Crate 1",
        "Technical Difficulties - Arena 4 Crate 2",
    ]), RWBYLocation)

    world.get_region("The Collapse").add_locations(get_location_names_with_ids([
        "The Collapse - Completed",
        "The Collapse - Golden Knight",
        "The Collapse - Golden Rook",
        "The Collapse - Black Knight",
        "The Collapse - Black Rook",
    ]), RWBYLocation)

    world.get_region("Below the Surface").add_locations(get_location_names_with_ids([
        "Below the Surface - Completed",
        "Below the Surface - Golden Knight",
        "Below the Surface - Golden Rook",
        "Below the Surface - Black Knight",
        "Below the Surface - Black Rook",
    ]), RWBYLocation)

    world.get_region("Right on Track").add_locations(get_location_names_with_ids([
        "Right on Track - Completed",
        "Right on Track - Golden Knight",
        "Right on Track - Golden Rook",
        "Right on Track - Black Knight",
        "Right on Track - Black Rook",
    ]), RWBYLocation)

    world.get_region("End of the Line").add_locations(get_location_names_with_ids([
        "End of the Line - Completed",
        "End of the Line - Golden Knight",
        "End of the Line - Golden Rook",
        "End of the Line - Black Knight",
        "End of the Line - Black Rook",
    ]), RWBYLocation)

    world.get_region("The Island of Dr. Merlot").add_locations(get_location_names_with_ids([
        "The Island of Dr. Merlot - Completed",
        "The Island of Dr. Merlot - Golden Knight",
        "The Island of Dr. Merlot - Golden Rook",
        "The Island of Dr. Merlot - Black Knight",
        "The Island of Dr. Merlot - Black Rook",
    ]), RWBYLocation)

    world.get_region("A Grimm Discovery").add_locations(get_location_names_with_ids([
        "A Grimm Discovery - Completed",
        "A Grimm Discovery - Golden Knight",
        "A Grimm Discovery - Golden Rook",
        "A Grimm Discovery - Black Knight",
        "A Grimm Discovery - Black Rook",
    ]), RWBYLocation)

    world.get_region("The Grand Tour").add_locations(get_location_names_with_ids([
        "The Grand Tour - Completed",
        "The Grand Tour - Golden Knight",
        "The Grand Tour - Golden Rook",
        "The Grand Tour - Black Knight",
        "The Grand Tour - Black Rook",
    ]), RWBYLocation)

    world.get_region("Final Exam").add_locations(get_location_names_with_ids([
        "Final Exam - Completed",
        "Final Exam - Golden Knight",
        "Final Exam - Golden Rook",
        "Final Exam - Black Knight",
        "Final Exam - Black Rook",
    ]), RWBYLocation)

    world.get_region("Ruby Level Up").add_locations(get_location_names_with_ids([
        "Ruby Level 2",
        "Ruby Level 3",
        "Ruby Level 4",
        "Ruby Level 5",
        "Ruby Level 6",
        "Ruby Level 7",
        "Ruby Level 8",
        "Ruby Level 9",
        "Ruby Level 10",
    ]), RWBYLocation)

    world.get_region("Weiss Level Up").add_locations(get_location_names_with_ids([
        "Weiss Level 2",
        "Weiss Level 3",
        "Weiss Level 4",
        "Weiss Level 5",
        "Weiss Level 6",
        "Weiss Level 7",
        "Weiss Level 8",
        "Weiss Level 9",
        "Weiss Level 10",
    ]), RWBYLocation)

    world.get_region("Blake Level Up").add_locations(get_location_names_with_ids([
        "Blake Level 2",
        "Blake Level 3",
        "Blake Level 4",
        "Blake Level 5",
        "Blake Level 6",
        "Blake Level 7",
        "Blake Level 8",
        "Blake Level 9",
        "Blake Level 10",
    ]), RWBYLocation)

    world.get_region("Yang Level Up").add_locations(get_location_names_with_ids([
        "Yang Level 2",
        "Yang Level 3",
        "Yang Level 4",
        "Yang Level 5",
        "Yang Level 6",
        "Yang Level 7",
        "Yang Level 8",
        "Yang Level 9",
        "Yang Level 10",
    ]), RWBYLocation)
